source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'Zopup_Example' do
  pod 'Zopup', :path => '../'

  target 'Zopup_Tests' do
    inherit! :search_paths

    
  end
end
